version: '3.7'

services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/node0/data:/var/gluster/data:Z
      - ./volumes/node0/state:/var/lib/glusterd:Z
      - ./start-master.sh:/root/start-master.sh:ro
    restart: unless-stopped
    depends_on:
      - node1
      - node2
    command: /root/start-master.sh node1 node2

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/node1/data:/var/gluster/data:Z
      - ./volumes/node1/state:/var/lib/glusterd:Z
    restart: unless-stopped

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/node2/data:/var/gluster/data:Z
      - ./volumes/node2/state:/var/lib/glusterd:Z
    restart: unless-stopped
