FROM archlinux as build

RUN pacman --noconfirm -Sy && \
    pacman --noconfirm -S wget base-devel rpcsvc-proto python2 liburcu
COPY install-gluster7.sh /root/
RUN /root/install-gluster7.sh



FROM archlinux as run

RUN pacman --noconfirm -Sy && \
    pacman --noconfirm -S grep libxml2 python2 liburcu which

COPY --from=build /opt/glusterfs /opt/glusterfs
COPY --from=build /sbin/mount.glusterfs /sbin/

COPY entrypoint.sh /root/entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
